use serde_json::json;

use crate::{
    application::{
        recommendations::{recommend_candidates, RecommendationRequest},
        review::{review_draft, DraftReviewRequest},
    },
    domain::{
        champion::{ExecutionDemand, LanePattern, Role},
        composition::CompositionIdentity,
    },
    tests::support::{bottom, draft_state, jungle, mid, support, top, ScenarioFixture},
};

fn fixtures() -> Vec<ScenarioFixture> {
    vec![
        ScenarioFixture {
            name: "protect_hypercarry",
            request: RecommendationRequest {
                draft_state: draft_state(
                    vec![
                        top(
                            "Ornn",
                            vec![
                                CompositionIdentity::Engage,
                                CompositionIdentity::FrontToBack,
                            ],
                            ExecutionDemand::Low,
                            5,
                            4,
                            5,
                            1,
                            4,
                            LanePattern::Stable,
                        ),
                        jungle(
                            "Sejuani",
                            vec![
                                CompositionIdentity::Engage,
                                CompositionIdentity::FrontToBack,
                                CompositionIdentity::Pick,
                            ],
                            ExecutionDemand::Low,
                            5,
                            3,
                            4,
                            2,
                            5,
                        ),
                        mid(
                            "Azir",
                            vec![CompositionIdentity::FrontToBack, CompositionIdentity::Poke],
                            ExecutionDemand::High,
                            1,
                            5,
                            1,
                            2,
                            2,
                            LanePattern::Scaling,
                        ),
                        bottom(
                            "Jinx",
                            vec![
                                CompositionIdentity::FrontToBack,
                                CompositionIdentity::ProtectCarry,
                            ],
                            ExecutionDemand::Medium,
                            5,
                            1,
                        ),
                    ],
                    vec![
                        top(
                            "Renekton",
                            vec![CompositionIdentity::Skirmish],
                            ExecutionDemand::Low,
                            2,
                            2,
                            3,
                            2,
                            2,
                            LanePattern::Bully,
                        ),
                        jungle(
                            "Vi",
                            vec![CompositionIdentity::Engage, CompositionIdentity::Pick],
                            ExecutionDemand::Low,
                            4,
                            2,
                            3,
                            3,
                            3,
                        ),
                    ],
                    vec![Role::Support],
                ),
                candidates: vec![
                    support(
                        "Lulu",
                        vec![CompositionIdentity::ProtectCarry],
                        ExecutionDemand::Low,
                        0,
                        4,
                        1,
                        2,
                        2,
                    ),
                    support(
                        "Braum",
                        vec![
                            CompositionIdentity::ProtectCarry,
                            CompositionIdentity::FrontToBack,
                        ],
                        ExecutionDemand::Low,
                        1,
                        3,
                        4,
                        1,
                        4,
                    ),
                    support(
                        "Renata",
                        vec![CompositionIdentity::ProtectCarry, CompositionIdentity::Pick],
                        ExecutionDemand::Medium,
                        1,
                        3,
                        2,
                        1,
                        3,
                    ),
                    support(
                        "Nautilus",
                        vec![CompositionIdentity::Engage, CompositionIdentity::Pick],
                        ExecutionDemand::Low,
                        5,
                        2,
                        4,
                        1,
                        5,
                    ),
                    support(
                        "Pyke",
                        vec![CompositionIdentity::Pick],
                        ExecutionDemand::High,
                        1,
                        2,
                        1,
                        4,
                        3,
                    ),
                ],
            },
            preferences: json!({"style": "protect_carry", "risk": "low"}),
            expected_top_3: ["Braum", "Lulu", "Nautilus"],
            expected_alert_codes: &[],
            expected_identities: &[
                CompositionIdentity::Engage,
                CompositionIdentity::FrontToBack,
                CompositionIdentity::Pick,
                CompositionIdentity::Poke,
                CompositionIdentity::ProtectCarry,
            ],
            expected_win_condition_fragment: "front-to-back",
        },
        ScenarioFixture {
            name: "plan_flou",
            request: RecommendationRequest {
                draft_state: draft_state(
                    vec![
                        top(
                            "Jayce",
                            vec![CompositionIdentity::Poke, CompositionIdentity::Siege],
                            ExecutionDemand::Medium,
                            1,
                            3,
                            2,
                            2,
                            1,
                            LanePattern::Bully,
                        ),
                        jungle(
                            "Viego",
                            vec![CompositionIdentity::Skirmish],
                            ExecutionDemand::Medium,
                            1,
                            3,
                            2,
                            3,
                            1,
                        ),
                        mid(
                            "Ahri",
                            vec![CompositionIdentity::Pick, CompositionIdentity::Skirmish],
                            ExecutionDemand::Medium,
                            2,
                            3,
                            1,
                            4,
                            3,
                            LanePattern::Roaming,
                        ),
                        bottom(
                            "Ezreal",
                            vec![CompositionIdentity::Poke],
                            ExecutionDemand::Medium,
                            3,
                            3,
                        ),
                    ],
                    vec![mid(
                        "Orianna",
                        vec![CompositionIdentity::FrontToBack],
                        ExecutionDemand::Low,
                        1,
                        4,
                        1,
                        1,
                        2,
                        LanePattern::Scaling,
                    )],
                    vec![Role::Support],
                ),
                candidates: vec![
                    support(
                        "Nautilus",
                        vec![CompositionIdentity::Engage, CompositionIdentity::Pick],
                        ExecutionDemand::Low,
                        5,
                        2,
                        4,
                        1,
                        5,
                    ),
                    support(
                        "Leona",
                        vec![CompositionIdentity::Engage],
                        ExecutionDemand::Low,
                        5,
                        2,
                        4,
                        1,
                        5,
                    ),
                    support(
                        "Renata",
                        vec![CompositionIdentity::ProtectCarry, CompositionIdentity::Pick],
                        ExecutionDemand::Medium,
                        1,
                        3,
                        2,
                        1,
                        3,
                    ),
                    support(
                        "Bard",
                        vec![CompositionIdentity::Pick, CompositionIdentity::Skirmish],
                        ExecutionDemand::High,
                        1,
                        3,
                        1,
                        4,
                        2,
                    ),
                    support(
                        "Karma",
                        vec![CompositionIdentity::Poke, CompositionIdentity::ProtectCarry],
                        ExecutionDemand::Low,
                        0,
                        3,
                        1,
                        2,
                        2,
                    ),
                ],
            },
            preferences: json!({"style": "engage_needed", "risk": "medium"}),
            expected_top_3: ["Nautilus", "Leona", "Renata"],
            expected_alert_codes: &["missing_primary_engage"],
            expected_identities: &[
                CompositionIdentity::Pick,
                CompositionIdentity::Poke,
                CompositionIdentity::Siege,
                CompositionIdentity::Skirmish,
            ],
            expected_win_condition_fragment: "surnombres",
        },
        ScenarioFixture {
            name: "double_tank_sans_tank_shred",
            request: RecommendationRequest {
                draft_state: draft_state(
                    vec![
                        top(
                            "Ornn",
                            vec![
                                CompositionIdentity::Engage,
                                CompositionIdentity::FrontToBack,
                            ],
                            ExecutionDemand::Low,
                            5,
                            4,
                            5,
                            1,
                            4,
                            LanePattern::Stable,
                        ),
                        jungle(
                            "Sejuani",
                            vec![
                                CompositionIdentity::Engage,
                                CompositionIdentity::FrontToBack,
                            ],
                            ExecutionDemand::Low,
                            5,
                            3,
                            4,
                            2,
                            5,
                        ),
                        mid(
                            "Orianna",
                            vec![CompositionIdentity::FrontToBack],
                            ExecutionDemand::Low,
                            1,
                            4,
                            1,
                            1,
                            3,
                            LanePattern::Scaling,
                        ),
                        bottom(
                            "KaiSa",
                            vec![CompositionIdentity::FrontToBack],
                            ExecutionDemand::Medium,
                            4,
                            3,
                        ),
                    ],
                    vec![
                        top(
                            "Sion",
                            vec![CompositionIdentity::FrontToBack],
                            ExecutionDemand::Low,
                            4,
                            4,
                            5,
                            1,
                            4,
                            LanePattern::Stable,
                        ),
                        jungle(
                            "Maokai",
                            vec![
                                CompositionIdentity::Engage,
                                CompositionIdentity::FrontToBack,
                            ],
                            ExecutionDemand::Low,
                            4,
                            3,
                            5,
                            1,
                            5,
                        ),
                    ],
                    vec![Role::Support],
                ),
                candidates: vec![
                    support(
                        "Braum",
                        vec![
                            CompositionIdentity::ProtectCarry,
                            CompositionIdentity::FrontToBack,
                        ],
                        ExecutionDemand::Low,
                        1,
                        3,
                        4,
                        1,
                        4,
                    ),
                    support(
                        "Renata",
                        vec![CompositionIdentity::ProtectCarry, CompositionIdentity::Pick],
                        ExecutionDemand::Medium,
                        1,
                        3,
                        2,
                        1,
                        3,
                    ),
                    support(
                        "Nautilus",
                        vec![CompositionIdentity::Engage, CompositionIdentity::Pick],
                        ExecutionDemand::Low,
                        5,
                        2,
                        4,
                        1,
                        5,
                    ),
                    support(
                        "Zyra",
                        vec![CompositionIdentity::Poke, CompositionIdentity::Siege],
                        ExecutionDemand::Medium,
                        0,
                        3,
                        1,
                        1,
                        3,
                    ),
                    support(
                        "Brand",
                        vec![CompositionIdentity::Poke],
                        ExecutionDemand::High,
                        0,
                        3,
                        1,
                        1,
                        2,
                    ),
                ],
            },
            preferences: json!({"style": "front_to_back", "need": "steady_dps"}),
            expected_top_3: ["Braum", "Nautilus", "Renata"],
            expected_alert_codes: &[],
            expected_identities: &[
                CompositionIdentity::Engage,
                CompositionIdentity::FrontToBack,
            ],
            expected_win_condition_fragment: "front-to-back",
        },
        ScenarioFixture {
            name: "zone_control_setup_objectif",
            request: RecommendationRequest {
                draft_state: draft_state(
                    vec![
                        top(
                            "Rumble",
                            vec![CompositionIdentity::Poke, CompositionIdentity::Skirmish],
                            ExecutionDemand::Medium,
                            2,
                            3,
                            2,
                            1,
                            3,
                            LanePattern::Bully,
                        ),
                        jungle(
                            "Maokai",
                            vec![
                                CompositionIdentity::Engage,
                                CompositionIdentity::FrontToBack,
                            ],
                            ExecutionDemand::Low,
                            4,
                            3,
                            5,
                            1,
                            5,
                        ),
                        mid(
                            "Orianna",
                            vec![CompositionIdentity::FrontToBack],
                            ExecutionDemand::Low,
                            1,
                            4,
                            1,
                            1,
                            3,
                            LanePattern::Scaling,
                        ),
                        bottom(
                            "Varus",
                            vec![CompositionIdentity::Poke],
                            ExecutionDemand::Medium,
                            3,
                            1,
                        ),
                    ],
                    vec![jungle(
                        "LeeSin",
                        vec![CompositionIdentity::Skirmish],
                        ExecutionDemand::Medium,
                        2,
                        2,
                        2,
                        3,
                        2,
                    )],
                    vec![Role::Support],
                ),
                candidates: vec![
                    support(
                        "Nautilus",
                        vec![CompositionIdentity::Engage, CompositionIdentity::Pick],
                        ExecutionDemand::Low,
                        5,
                        2,
                        4,
                        1,
                        5,
                    ),
                    support(
                        "Braum",
                        vec![
                            CompositionIdentity::ProtectCarry,
                            CompositionIdentity::FrontToBack,
                        ],
                        ExecutionDemand::Low,
                        1,
                        3,
                        4,
                        1,
                        4,
                    ),
                    support(
                        "Renata",
                        vec![CompositionIdentity::ProtectCarry, CompositionIdentity::Pick],
                        ExecutionDemand::Medium,
                        1,
                        3,
                        2,
                        1,
                        3,
                    ),
                    support(
                        "Karma",
                        vec![CompositionIdentity::Poke, CompositionIdentity::ProtectCarry],
                        ExecutionDemand::Low,
                        0,
                        3,
                        1,
                        2,
                        2,
                    ),
                    support(
                        "Bard",
                        vec![CompositionIdentity::Pick, CompositionIdentity::Skirmish],
                        ExecutionDemand::High,
                        1,
                        3,
                        1,
                        4,
                        2,
                    ),
                ],
            },
            preferences: json!({"objective_setup": true, "vision_first": true}),
            expected_top_3: ["Nautilus", "Braum", "Renata"],
            expected_alert_codes: &[],
            expected_identities: &[
                CompositionIdentity::Engage,
                CompositionIdentity::FrontToBack,
                CompositionIdentity::Poke,
                CompositionIdentity::Skirmish,
            ],
            expected_win_condition_fragment: "objectifs",
        },
        ScenarioFixture {
            name: "split_qui_casse_la_coherence",
            request: RecommendationRequest {
                draft_state: draft_state(
                    vec![
                        jungle(
                            "Sejuani",
                            vec![
                                CompositionIdentity::Engage,
                                CompositionIdentity::FrontToBack,
                            ],
                            ExecutionDemand::Low,
                            5,
                            3,
                            4,
                            2,
                            5,
                        ),
                        mid(
                            "Orianna",
                            vec![CompositionIdentity::FrontToBack],
                            ExecutionDemand::Low,
                            1,
                            4,
                            1,
                            1,
                            3,
                            LanePattern::Scaling,
                        ),
                        bottom(
                            "Aphelios",
                            vec![
                                CompositionIdentity::FrontToBack,
                                CompositionIdentity::ProtectCarry,
                            ],
                            ExecutionDemand::High,
                            5,
                            1,
                        ),
                        support(
                            "Braum",
                            vec![
                                CompositionIdentity::ProtectCarry,
                                CompositionIdentity::FrontToBack,
                            ],
                            ExecutionDemand::Low,
                            1,
                            3,
                            4,
                            1,
                            4,
                        ),
                    ],
                    vec![mid(
                        "Syndra",
                        vec![CompositionIdentity::Pick],
                        ExecutionDemand::Medium,
                        1,
                        3,
                        1,
                        2,
                        3,
                        LanePattern::Bully,
                    )],
                    vec![Role::Top],
                ),
                candidates: vec![
                    top(
                        "Ornn",
                        vec![
                            CompositionIdentity::Engage,
                            CompositionIdentity::FrontToBack,
                        ],
                        ExecutionDemand::Low,
                        5,
                        4,
                        5,
                        1,
                        4,
                        LanePattern::Stable,
                    ),
                    top(
                        "Ksante",
                        vec![
                            CompositionIdentity::Engage,
                            CompositionIdentity::FrontToBack,
                        ],
                        ExecutionDemand::High,
                        4,
                        4,
                        4,
                        2,
                        4,
                        LanePattern::Stable,
                    ),
                    top(
                        "Gnar",
                        vec![
                            CompositionIdentity::FrontToBack,
                            CompositionIdentity::Skirmish,
                        ],
                        ExecutionDemand::Medium,
                        3,
                        3,
                        3,
                        3,
                        3,
                        LanePattern::Stable,
                    ),
                    top(
                        "Jax",
                        vec![
                            CompositionIdentity::SplitPush,
                            CompositionIdentity::Skirmish,
                        ],
                        ExecutionDemand::Medium,
                        1,
                        4,
                        3,
                        3,
                        1,
                        LanePattern::Scaling,
                    ),
                    top(
                        "Fiora",
                        vec![CompositionIdentity::SplitPush],
                        ExecutionDemand::High,
                        0,
                        4,
                        2,
                        4,
                        1,
                        LanePattern::Bully,
                    ),
                ],
            },
            preferences: json!({"style": "5v5", "avoid_split": true}),
            expected_top_3: ["Ornn", "Gnar", "Ksante"],
            expected_alert_codes: &[],
            expected_identities: &[
                CompositionIdentity::Engage,
                CompositionIdentity::FrontToBack,
                CompositionIdentity::ProtectCarry,
            ],
            expected_win_condition_fragment: "front-to-back",
        },
        ScenarioFixture {
            name: "engage_vs_poke",
            request: RecommendationRequest {
                draft_state: draft_state(
                    vec![
                        top(
                            "Sion",
                            vec![
                                CompositionIdentity::Engage,
                                CompositionIdentity::FrontToBack,
                            ],
                            ExecutionDemand::Low,
                            4,
                            4,
                            5,
                            1,
                            4,
                            LanePattern::Stable,
                        ),
                        jungle(
                            "Sejuani",
                            vec![
                                CompositionIdentity::Engage,
                                CompositionIdentity::FrontToBack,
                            ],
                            ExecutionDemand::Low,
                            5,
                            3,
                            4,
                            2,
                            5,
                        ),
                        mid(
                            "Orianna",
                            vec![CompositionIdentity::FrontToBack],
                            ExecutionDemand::Low,
                            1,
                            4,
                            1,
                            1,
                            3,
                            LanePattern::Scaling,
                        ),
                        bottom(
                            "Xayah",
                            vec![CompositionIdentity::FrontToBack],
                            ExecutionDemand::Medium,
                            4,
                            3,
                        ),
                    ],
                    vec![
                        top(
                            "Jayce",
                            vec![CompositionIdentity::Poke, CompositionIdentity::Siege],
                            ExecutionDemand::Medium,
                            1,
                            3,
                            2,
                            2,
                            1,
                            LanePattern::Bully,
                        ),
                        mid(
                            "Ziggs",
                            vec![CompositionIdentity::Poke, CompositionIdentity::Siege],
                            ExecutionDemand::Low,
                            0,
                            3,
                            1,
                            1,
                            2,
                            LanePattern::Utility,
                        ),
                    ],
                    vec![Role::Support],
                ),
                candidates: vec![
                    support(
                        "Nautilus",
                        vec![CompositionIdentity::Engage, CompositionIdentity::Pick],
                        ExecutionDemand::Low,
                        5,
                        2,
                        4,
                        1,
                        5,
                    ),
                    support(
                        "Rell",
                        vec![
                            CompositionIdentity::Engage,
                            CompositionIdentity::FrontToBack,
                        ],
                        ExecutionDemand::Medium,
                        5,
                        2,
                        4,
                        2,
                        5,
                    ),
                    support(
                        "Braum",
                        vec![
                            CompositionIdentity::ProtectCarry,
                            CompositionIdentity::FrontToBack,
                        ],
                        ExecutionDemand::Low,
                        1,
                        3,
                        4,
                        1,
                        4,
                    ),
                    support(
                        "Karma",
                        vec![CompositionIdentity::Poke, CompositionIdentity::ProtectCarry],
                        ExecutionDemand::Low,
                        0,
                        3,
                        1,
                        2,
                        2,
                    ),
                    support(
                        "Pyke",
                        vec![CompositionIdentity::Pick],
                        ExecutionDemand::High,
                        1,
                        2,
                        1,
                        4,
                        3,
                    ),
                ],
            },
            preferences: json!({"enemy_style": "poke", "force_engage": true}),
            expected_top_3: ["Nautilus", "Braum", "Rell"],
            expected_alert_codes: &[],
            expected_identities: &[
                CompositionIdentity::Engage,
                CompositionIdentity::FrontToBack,
            ],
            expected_win_condition_fragment: "objectifs",
        },
        ScenarioFixture {
            name: "anti_dive_scaling",
            request: RecommendationRequest {
                draft_state: draft_state(
                    vec![
                        top(
                            "Ksante",
                            vec![
                                CompositionIdentity::Engage,
                                CompositionIdentity::FrontToBack,
                            ],
                            ExecutionDemand::High,
                            4,
                            4,
                            4,
                            2,
                            4,
                            LanePattern::Stable,
                        ),
                        jungle(
                            "Poppy",
                            vec![
                                CompositionIdentity::FrontToBack,
                                CompositionIdentity::ProtectCarry,
                            ],
                            ExecutionDemand::Low,
                            2,
                            3,
                            4,
                            2,
                            4,
                        ),
                        mid(
                            "Azir",
                            vec![CompositionIdentity::FrontToBack, CompositionIdentity::Poke],
                            ExecutionDemand::High,
                            1,
                            5,
                            1,
                            2,
                            2,
                            LanePattern::Scaling,
                        ),
                        bottom(
                            "Jinx",
                            vec![
                                CompositionIdentity::FrontToBack,
                                CompositionIdentity::ProtectCarry,
                            ],
                            ExecutionDemand::Medium,
                            5,
                            1,
                        ),
                    ],
                    vec![
                        jungle(
                            "Vi",
                            vec![CompositionIdentity::Engage, CompositionIdentity::Pick],
                            ExecutionDemand::Low,
                            4,
                            2,
                            3,
                            3,
                            3,
                        ),
                        mid(
                            "Akali",
                            vec![CompositionIdentity::Pick, CompositionIdentity::Skirmish],
                            ExecutionDemand::High,
                            1,
                            3,
                            1,
                            4,
                            2,
                            LanePattern::Roaming,
                        ),
                    ],
                    vec![Role::Support],
                ),
                candidates: vec![
                    support(
                        "Braum",
                        vec![
                            CompositionIdentity::ProtectCarry,
                            CompositionIdentity::FrontToBack,
                        ],
                        ExecutionDemand::Low,
                        1,
                        3,
                        4,
                        1,
                        4,
                    ),
                    support(
                        "Lulu",
                        vec![CompositionIdentity::ProtectCarry],
                        ExecutionDemand::Low,
                        0,
                        4,
                        1,
                        2,
                        2,
                    ),
                    support(
                        "Renata",
                        vec![CompositionIdentity::ProtectCarry, CompositionIdentity::Pick],
                        ExecutionDemand::Medium,
                        1,
                        3,
                        2,
                        1,
                        3,
                    ),
                    support(
                        "Nautilus",
                        vec![CompositionIdentity::Engage, CompositionIdentity::Pick],
                        ExecutionDemand::Low,
                        5,
                        2,
                        4,
                        1,
                        5,
                    ),
                    support(
                        "Pyke",
                        vec![CompositionIdentity::Pick],
                        ExecutionDemand::High,
                        1,
                        2,
                        1,
                        4,
                        3,
                    ),
                ],
            },
            preferences: json!({"anti_dive": true, "scale": true}),
            expected_top_3: ["Braum", "Lulu", "Renata"],
            expected_alert_codes: &[],
            expected_identities: &[
                CompositionIdentity::Engage,
                CompositionIdentity::FrontToBack,
                CompositionIdentity::Poke,
                CompositionIdentity::ProtectCarry,
            ],
            expected_win_condition_fragment: "front-to-back",
        },
        ScenarioFixture {
            name: "pick_comp_sans_follow",
            request: RecommendationRequest {
                draft_state: draft_state(
                    vec![
                        top(
                            "Jayce",
                            vec![CompositionIdentity::Poke, CompositionIdentity::Siege],
                            ExecutionDemand::Medium,
                            1,
                            3,
                            2,
                            2,
                            1,
                            LanePattern::Bully,
                        ),
                        jungle(
                            "Elise",
                            vec![CompositionIdentity::Pick, CompositionIdentity::Skirmish],
                            ExecutionDemand::High,
                            1,
                            2,
                            1,
                            3,
                            3,
                        ),
                        mid(
                            "Ahri",
                            vec![CompositionIdentity::Pick, CompositionIdentity::Skirmish],
                            ExecutionDemand::Medium,
                            2,
                            3,
                            1,
                            4,
                            3,
                            LanePattern::Roaming,
                        ),
                        bottom(
                            "Ezreal",
                            vec![CompositionIdentity::Poke],
                            ExecutionDemand::Medium,
                            3,
                            3,
                        ),
                    ],
                    vec![mid(
                        "Lissandra",
                        vec![CompositionIdentity::Pick],
                        ExecutionDemand::Low,
                        2,
                        3,
                        2,
                        1,
                        4,
                        LanePattern::Utility,
                    )],
                    vec![Role::Support],
                ),
                candidates: vec![
                    support(
                        "Nautilus",
                        vec![CompositionIdentity::Engage, CompositionIdentity::Pick],
                        ExecutionDemand::Low,
                        5,
                        2,
                        4,
                        1,
                        5,
                    ),
                    support(
                        "Leona",
                        vec![CompositionIdentity::Engage],
                        ExecutionDemand::Low,
                        5,
                        2,
                        4,
                        1,
                        5,
                    ),
                    support(
                        "Bard",
                        vec![CompositionIdentity::Pick, CompositionIdentity::Skirmish],
                        ExecutionDemand::High,
                        1,
                        3,
                        1,
                        4,
                        2,
                    ),
                    support(
                        "Karma",
                        vec![CompositionIdentity::Poke, CompositionIdentity::ProtectCarry],
                        ExecutionDemand::Low,
                        0,
                        3,
                        1,
                        2,
                        2,
                    ),
                    support(
                        "Renata",
                        vec![CompositionIdentity::ProtectCarry, CompositionIdentity::Pick],
                        ExecutionDemand::Medium,
                        1,
                        3,
                        2,
                        1,
                        3,
                    ),
                ],
            },
            preferences: json!({"catch": true, "need_follow_up": true}),
            expected_top_3: ["Nautilus", "Leona", "Renata"],
            expected_alert_codes: &["missing_primary_engage"],
            expected_identities: &[
                CompositionIdentity::Pick,
                CompositionIdentity::Poke,
                CompositionIdentity::Siege,
                CompositionIdentity::Skirmish,
            ],
            expected_win_condition_fragment: "surnombres",
        },
        ScenarioFixture {
            name: "front_to_back",
            request: RecommendationRequest {
                draft_state: draft_state(
                    vec![
                        top(
                            "Ornn",
                            vec![
                                CompositionIdentity::Engage,
                                CompositionIdentity::FrontToBack,
                            ],
                            ExecutionDemand::Low,
                            5,
                            4,
                            5,
                            1,
                            4,
                            LanePattern::Stable,
                        ),
                        jungle(
                            "Sejuani",
                            vec![
                                CompositionIdentity::Engage,
                                CompositionIdentity::FrontToBack,
                            ],
                            ExecutionDemand::Low,
                            5,
                            3,
                            4,
                            2,
                            5,
                        ),
                        mid(
                            "Orianna",
                            vec![CompositionIdentity::FrontToBack],
                            ExecutionDemand::Low,
                            1,
                            4,
                            1,
                            1,
                            3,
                            LanePattern::Scaling,
                        ),
                        bottom(
                            "Smolder",
                            vec![
                                CompositionIdentity::FrontToBack,
                                CompositionIdentity::ProtectCarry,
                            ],
                            ExecutionDemand::Medium,
                            5,
                            2,
                        ),
                    ],
                    vec![mid(
                        "Taliyah",
                        vec![CompositionIdentity::Pick],
                        ExecutionDemand::Medium,
                        2,
                        3,
                        1,
                        2,
                        3,
                        LanePattern::Roaming,
                    )],
                    vec![Role::Support],
                ),
                candidates: vec![
                    support(
                        "Braum",
                        vec![
                            CompositionIdentity::ProtectCarry,
                            CompositionIdentity::FrontToBack,
                        ],
                        ExecutionDemand::Low,
                        1,
                        3,
                        4,
                        1,
                        4,
                    ),
                    support(
                        "Nautilus",
                        vec![CompositionIdentity::Engage, CompositionIdentity::Pick],
                        ExecutionDemand::Low,
                        5,
                        2,
                        4,
                        1,
                        5,
                    ),
                    support(
                        "Renata",
                        vec![CompositionIdentity::ProtectCarry, CompositionIdentity::Pick],
                        ExecutionDemand::Medium,
                        1,
                        3,
                        2,
                        1,
                        3,
                    ),
                    support(
                        "Lulu",
                        vec![CompositionIdentity::ProtectCarry],
                        ExecutionDemand::Low,
                        0,
                        4,
                        1,
                        2,
                        2,
                    ),
                    support(
                        "Pyke",
                        vec![CompositionIdentity::Pick],
                        ExecutionDemand::High,
                        1,
                        2,
                        1,
                        4,
                        3,
                    ),
                ],
            },
            preferences: json!({"style": "front_to_back", "teamfight": true}),
            expected_top_3: ["Braum", "Nautilus", "Lulu"],
            expected_alert_codes: &[],
            expected_identities: &[
                CompositionIdentity::Engage,
                CompositionIdentity::FrontToBack,
                CompositionIdentity::ProtectCarry,
            ],
            expected_win_condition_fragment: "front-to-back",
        },
        ScenarioFixture {
            name: "comp_trop_difficile_a_executer",
            request: RecommendationRequest {
                draft_state: draft_state(
                    vec![
                        top(
                            "Jayce",
                            vec![CompositionIdentity::Poke, CompositionIdentity::Siege],
                            ExecutionDemand::High,
                            1,
                            3,
                            2,
                            2,
                            1,
                            LanePattern::Bully,
                        ),
                        jungle(
                            "Nidalee",
                            vec![CompositionIdentity::Poke, CompositionIdentity::Skirmish],
                            ExecutionDemand::High,
                            1,
                            3,
                            1,
                            4,
                            1,
                        ),
                        mid(
                            "Azir",
                            vec![CompositionIdentity::FrontToBack, CompositionIdentity::Poke],
                            ExecutionDemand::High,
                            1,
                            5,
                            1,
                            2,
                            2,
                            LanePattern::Scaling,
                        ),
                        bottom(
                            "Ezreal",
                            vec![CompositionIdentity::Poke],
                            ExecutionDemand::Medium,
                            3,
                            3,
                        ),
                    ],
                    vec![
                        top(
                            "Malphite",
                            vec![CompositionIdentity::Engage],
                            ExecutionDemand::Low,
                            5,
                            3,
                            4,
                            1,
                            4,
                            LanePattern::Stable,
                        ),
                        jungle(
                            "Vi",
                            vec![CompositionIdentity::Engage, CompositionIdentity::Pick],
                            ExecutionDemand::Low,
                            4,
                            2,
                            3,
                            3,
                            3,
                        ),
                        mid(
                            "Lissandra",
                            vec![CompositionIdentity::Pick],
                            ExecutionDemand::Low,
                            2,
                            3,
                            2,
                            1,
                            4,
                            LanePattern::Utility,
                        ),
                    ],
                    vec![Role::Support],
                ),
                candidates: vec![
                    support(
                        "Nautilus",
                        vec![CompositionIdentity::Engage, CompositionIdentity::Pick],
                        ExecutionDemand::Low,
                        5,
                        2,
                        4,
                        1,
                        5,
                    ),
                    support(
                        "Leona",
                        vec![CompositionIdentity::Engage],
                        ExecutionDemand::Low,
                        5,
                        2,
                        4,
                        1,
                        5,
                    ),
                    support(
                        "Braum",
                        vec![
                            CompositionIdentity::ProtectCarry,
                            CompositionIdentity::FrontToBack,
                        ],
                        ExecutionDemand::Low,
                        1,
                        3,
                        4,
                        1,
                        4,
                    ),
                    support(
                        "Pyke",
                        vec![CompositionIdentity::Pick],
                        ExecutionDemand::High,
                        1,
                        2,
                        1,
                        4,
                        3,
                    ),
                    support(
                        "Bard",
                        vec![CompositionIdentity::Pick, CompositionIdentity::Skirmish],
                        ExecutionDemand::High,
                        1,
                        3,
                        1,
                        4,
                        2,
                    ),
                ],
            },
            preferences: json!({"simplify_execution": true, "stage": true}),
            expected_top_3: ["Nautilus", "Leona", "Braum"],
            expected_alert_codes: &["missing_primary_engage"],
            expected_identities: &[
                CompositionIdentity::FrontToBack,
                CompositionIdentity::Poke,
                CompositionIdentity::Siege,
                CompositionIdentity::Skirmish,
            ],
            expected_win_condition_fragment: "objectifs",
        },
    ]
}

#[test]
fn scenario_matrix_keeps_expected_rankings_and_messages() {
    for fixture in fixtures() {
        assert!(
            fixture.preferences.is_object(),
            "{}: preferences should be stored as object",
            fixture.name
        );

        let response = recommend_candidates(fixture.request.clone());
        let review = review_draft(DraftReviewRequest {
            draft_state: fixture.request.draft_state.clone(),
        });

        let actual_top_3 = response
            .top_5
            .iter()
            .take(3)
            .map(|entry| entry.champion.name.as_str())
            .collect::<Vec<_>>();
        assert_eq!(
            actual_top_3, fixture.expected_top_3,
            "scenario {}",
            fixture.name
        );

        let actual_alert_codes = response
            .composition
            .alerts
            .iter()
            .map(|alert| alert.code.as_str())
            .collect::<Vec<_>>();
        assert_eq!(
            actual_alert_codes, fixture.expected_alert_codes,
            "scenario {}",
            fixture.name
        );

        assert_eq!(
            response.composition.identities, fixture.expected_identities,
            "scenario {}",
            fixture.name
        );

        assert!(
            response.top_5[0]
                .win_condition_after_pick
                .to_lowercase()
                .contains(&fixture.expected_win_condition_fragment.to_lowercase()),
            "scenario {}",
            fixture.name
        );

        assert!(
            !review.win_condition.is_empty(),
            "scenario {}",
            fixture.name
        );
    }
}
